# Build the project using the Bitcraze builder docker image
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build to make sure dependencies are OK
    - cron:  '30 19 * * 5'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check and build
      run: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build

  windows:
    runs-on: windows-2019
    needs: checks

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -e .[pyqt5]
          pip install cx_freeze~=6.15
          pip install jinja2
          choco install -y nsis.portable -version 3.02.0.20160720
      - name: Build
        run: python cx_setup.py build
      - name: Build installer
        run: |
          python win32install\generate_nsis.py
          makensis win32install\lpstools.nsi
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: windows-build
          path: "win32install/*.exe"
